language: php

dist: trusty

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot

matrix:
  include:
    - php: 5.5
      env: dependencies="--prefer-lowest --prefer-stable"
    - php: 7
      env: dependencies="--prefer-lowest --prefer-stable"

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer update --no-interaction $dependencies
  - composer require symfony/event-dispatcher:^2.8

before_script:
  - mkdir -p src-tests/logs/
  - mkdir -p src-tests/coverage/

script:
  - cd src-tests && ../vendor/bin/phpunit --coverage-clover ./logs/clover.xml
  - cd .. && vendor/bin/phpcs --standard=ruleset.xml

after_success:
  - travis_retry php vendor/bin/coveralls -v
